name: 'Sample'
on:
  push:
    branches:
      - main
    tags:
      # sample-v0.1.0
      # - sample-v[0-9].[0-9].[0-9].* # 発火しない
      # - 'sample-v[0-9].[0-9].[0-9].*' # 発火しない
      # - sample-v[0-9]+\.[0-9]+\.[0-9]+.* #発火しない
      # - 'sample-v[0-9]+\.[0-9]+\.[0-9]+.*'
      - sample-v[0-9]+.[0-9]+.[0-9]+** # sample-v0.5.0で発火した #リリースノートでも発火
    paths:
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          echo "Event: ${{ github.event_name }}"
